### ISSUE TITLE
[Wiki] Implement mobile site

### ISSUE THREAD

**Issue by KevinPayravi** [KevinPayravi/Nookipedia.com#2]
Many NIWA wikis are implementing mobile versions of their site through Wikimedia's official mobile option.

**Comment by jake8** [comment]
I tried doing this on Wikisimpsons, and it worked, but it ended up not being a good option for us. Many pages including the Main Page displayed poorly on mobile and required scrolling. The documentation provided for setting up a separate main page didn't work at all no matter how I configured it. Worst of all, it turns out the RPM and CPC for mobile ads is far lower than desktop ones, and we saw a significant dip in revenue to the point where the site would be unsustainable. (We'd probably have better luck just creating native iOS/Android apps, but that's too large of a project to take on right now.)  For these reasons, I'm going to have to put a hold on this suggestion until further notice.
